
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 04 23:38:31 ART 2016
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPOSED = 11;
  public static final int RKEY = 4;
  public static final int SEPARATOR = 2;
  public static final int LITERAL = 12;
  public static final int EOF = 0;
  public static final int LKEY = 3;
  public static final int NESTED = 10;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int SEMICOLON = 7;
  public static final int IDENTIFIER = 13;
  public static final int TEXT = 8;
  public static final int BEGIN = 9;
  public static final int LPAREN = 5;
}

