
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 15 16:40:00 ART 2018
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RKEY = 4;
  public static final int SEPARATOR = 2;
  public static final int LITERAL = 10;
  public static final int EOF = 0;
  public static final int LKEY = 3;
  public static final int NESTED = 9;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int IDENTIFIER = 11;
  public static final int TEXT = 7;
  public static final int BEGIN = 8;
  public static final int LPAREN = 5;
}

